# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master, development ]
  pull_request:
    branches: [ master, development ]
  release:
    branches: [ master, development ]
    # release types see : https://docs.github.com/en/actions/reference/events-that-trigger-workflows#release
    # he prereleased type will not trigger for pre-releases published from draft releases, but the published type will trigger.
    # If you want a workflow to run when stable and pre-releases publish, subscribe to published instead of released and prereleased.
    types: [published]

  schedule:
      # * is a special character in YAML, so you have to quote this string
      # | minute | hour (UTC) | day of month (1-31) | month (1-2) | day of week (0-6 or SUN-SAT)
      # every day at 05:40 am UTC - avoid 05:00 because of high load at the beginning of every hour
      - cron:  '40 5 * * *'


jobs:

  build:
    runs-on: ${{ matrix.os }}
{{PizzaCutter.gha.services}}{{PizzaCutter.option.delete_line_if_empty}}

    env:
        # prefix before commands - used for wine, there the prefix is "wine"
        cPREFIX: ""
        # command to launch python interpreter (it's different on macOS, there we need python3)
        cPYTHON: "python"
        # command to launch pip (it's different on macOS, there we need pip3)
        cPIP: "python -m pip"
        # switch off wine fix me messages
        WINEDEBUG: fixme-all

        # PYTEST
        PYTEST_DO_TESTS: "{{PizzaCutter.gha.pytest_do_tests}}"

        # FLAKE8 tests
        DO_FLAKE8_TESTS: "{{PizzaCutter.flake8_do_tests_in_gha}}"

        # MYPY tests
        MYPY_DO_TESTS: "{{PizzaCutter.gha.mypy_do_tests}}"
        MYPY_OPTIONS: "{{PizzaCutter.gha.mypy_options}}"
        MYPYPATH: "./{{PizzaCutter.package_dir}}/3rd_party_stubs"

        # coverage
        DO_COVERAGE: "{{PizzaCutter.gha.do_coverage}}"
        DO_COVERAGE_UPLOAD_CODECOV: "{{PizzaCutter.gha.do_coverage_upload_codecov}}"
        DO_COVERAGE_UPLOAD_CODE_CLIMATE: "{{PizzaCutter.gha.do_coverage_upload_code_climate}}"

        # package name
        PACKAGE_NAME: "{{PizzaCutter.package_name}}"
        # the registered CLI Command
        CLI_COMMAND: "{{PizzaCutter.shell_command}}"
        # the source file for rst_include (rebuild rst file includes)
        RST_INCLUDE_SOURCE: "{{PizzaCutter.gha.rst_include_source}}"
        # the target file for rst_include (rebuild rst file includes)
        RST_INCLUDE_TARGET: "{{PizzaCutter.gha.rst_include_target}}"
        # make Code Coverage Secret available in Environment
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        # make PyPi Password available in Environment
        PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}


    strategy:
      matrix:
        include:
          # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-software
          # https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#available-versions-of-python-and-pypy


  {{PizzaCutter.gha_windows_addon}}{{PizzaCutter.option.delete_line_if_empty}}
{{PizzaCutter.gha.linux.tests}}{{PizzaCutter.option.delete_line_if_empty}}
{{PizzaCutter.gha_osx_addon}}{{PizzaCutter.option.delete_line_if_empty}}
{{PizzaCutter.gha_wine_addon}}{{PizzaCutter.option.delete_line_if_empty}}

    name: "${{ matrix.os }} Python ${{ matrix.python-version }}"

    steps:
    # see : https://github.com/actions/checkout
    - uses: actions/checkout@v3

    - name: Setting up Python ${{ matrix.python-version }}
      # see: https://github.com/actions/setup-python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      # see: https://github.community/t/github-actions-new-bug-unable-to-create-environment-variables-based-matrix/16104/3
      env: ${{ matrix.env }}             # make matrix env variables accessible
      # lib_cicd_github install: upgrades pip, setuptools, wheel and pytest-pycodestyle
      run: |
        ${{ env.cPIP }} install git+https://github.com/bitranox/lib_cicd_github.git
        lib_cicd_github install

    - name: Debug - printenv and colortest
      env:
        # make matrix env variables accessible
        ${{ matrix.env }}
      shell: bash
      run: |
        # export for current step
        export "BRANCH=$(lib_cicd_github get_branch)"
        # export for subsequent steps
        echo "BRANCH=$BRANCH" >> $GITHUB_ENV
        log_util --level=SPAM  "working on branch $BRANCH"
        log_util --level=SPAM  "GITHUB_REF $GITHUB_REF"
        log_util --level=VERBOSE "github.base_ref: ${{ github.base_ref }}"
        log_util --level=VERBOSE "github.event: ${{ github.event }}"
        log_util --level=VERBOSE "github.event_name: ${{ github.event_name }}"
        log_util --level=VERBOSE "github.head_ref: ${{ github.head_ref }}"
        log_util --level=VERBOSE "github.job: ${{ github.job }}"
        log_util --level=VERBOSE "github.ref: ${{ github.ref }}"
        log_util --level=VERBOSE "github.repository: ${{ github.repository }}"
        log_util --level=VERBOSE "github.repository_owner: ${{ github.repository_owner }}"
        log_util --level=VERBOSE "runner.os: ${{ runner.os }}"
        log_util --level=VERBOSE "matrix.python-version: ${{ matrix.python-version }}"
        printenv
        log_util --colortest

    - name: Run Tests
      env:
        # make matrix env variables accessible
        ${{ matrix.env }}
      shell: bash
      run: |
        # export for current step
        export "BRANCH=$(lib_cicd_github get_branch)"
        # export for subsequent steps
        echo "BRANCH=$BRANCH" >> $GITHUB_ENV
        # run the tests
        lib_cicd_github script

    - name: After Success
      env:
        ${{matrix.env }}
      shell: bash
      continue-on-error: true
      run: |
        lib_cicd_github after_success

    - name: Deploy
      env:
        # see: https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#github-context
        # see : https://github.com/rlespinasse/github-slug-action
        # make matrix env variables accessible
        ${{matrix.env }}
      shell: bash
      run: |
        lib_cicd_github deploy
